# Generated by Django 5.2 on 2025-07-06 07:00

import apps.families.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.CharField(
                default=apps.families.models.Invitation._generate_code,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
