# Generated by Django 5.2 on 2025-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="completed",
        ),
        migrations.AddField(
            model_name="entry",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting", "Awaiting"),
                    ("completed", "Completed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("achieved", "Achieved"),
                ],
                default="awaiting",
                max_length=10,
            ),
        ),
    ]
